### ISSUE TITLE
build script & ci settings

### ISSUE THREAD

**Issue by koron** [vim-jp/vimdoc-en#1]
ref. https://github.com/vim-jp/vimdoc-ja-working

**Comment by k-takata** [comment]
I have committed scripts to the `master` branch and also locally generated html files to the `gh-pages` branch.
Unfortunately, the first build on Travis-CI failed. It failed to decrypt the deploy key.
https://travis-ci.org/vim-jp/vimdoc-en/builds/198476368#L141
Not sure what's wrong. Any ideas?

**Comment by koron** [comment]
How did you encrypt the key?

**Comment by k-takata** [comment]
See this commit message: f17de7a13ede968651f552f876f25f0b9b08bc0a
Maybe `travis encrypt-file` is better than `travis encrypt`?

**Comment by k-takata** [comment]
> See this commit message: f17de7a

I tried on Cygwin and Ubuntu 14.04, but both failed.

**Comment by k-takata** [comment]
I changed to use `travis encrypt-file` instead of `travis encrypt`, and it worked fine: 1251a5b961bedf814cebfd4f76bb4d7472a45f0d

However, unexpected changes were committed: 16d395ee49420a6c2ec058683a3c517212dfb668
It seems that `syntax/help.vim` comes with Ubuntu 14.04 is still old.

**Comment by k-takata** [comment]
> However, unexpected changes were committed: 16d395e
> It seems that syntax/help.vim comes with Ubuntu 14.04 is still old.

Fixed with the latest two commits: c6a3a559280784c3d30a778abcc9305c5eac5260, 8383ed28dc4f4a42ca1702103115c6f6a679b5a1

**Comment by k-takata** [comment]
I have also setup cron for this project on travis-ci.
I think we can close this now.
